# Generated by Django 4.2.13 on 2024-06-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShellCompleteTester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(db_index=True, default="", max_length=15),
                ),
                ("text_field", models.TextField(default="")),
                (
                    "float_field",
                    models.FloatField(db_index=True, default=None, null=True),
                ),
                (
                    "decimal_field",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=None,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("uuid_field", models.UUIDField(default=None, null=True, unique=True)),
                ("binary_field", models.BinaryField(default=None, null=True)),
                (
                    "ip_field",
                    models.GenericIPAddressField(
                        db_index=True, default=None, null=True
                    ),
                ),
                (
                    "email_field",
                    models.EmailField(
                        db_index=True, default=None, max_length=254, null=True
                    ),
                ),
                ("url_field", models.URLField(db_index=True, default=None, null=True)),
            ],
        ),
    ]
