# https://github.com/codecov/codecov-python/issues/136
coverage:
  fixes:
    - "__init__.py::django_typer/__init__.py"
    - "management/__init__.py::django_typer/management/__init__.py"
    - "utils.py::django_typer/utils.py"
